enableColors: true

enableNetwork: true

enableProgressBars: true

enableTransparentWorkspaces: true

httpRetry: 3

httpTimeout: 60000

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"
