nodeLinker: "node-modules"

# Enable transparent workspaces for better workspace dependency resolution
enableTransparentWorkspaces: true

# Enable network for package downloads
enableNetwork: true

# Timeout for HTTP requests (in milliseconds)
httpTimeout: 60000

# Number of retry attempts for HTTP requests
httpRetry: 3

# Registry configuration
npmRegistryServer: "https://registry.yarnpkg.com"

# Enable progress bars
enableProgressBars: true

# Enable colors in output
enableColors: true

# Prevent hoisting to avoid React Native issues
# This ensures React Native dependencies stay in their local node_modules
nmHoistingLimits: workspaces 