nodeLinker: "node-modules"

# Enable network for package downloads
enableNetwork: true

# Timeout for HTTP requests (in milliseconds)
httpTimeout: 60000

# Number of retry attempts for HTTP requests
httpRetry: 3

# Registry configuration
npmRegistryServer: "https://registry.yarnpkg.com"

# Enable progress bars
enableProgressBars: true

# Enable colors in output
enableColors: true 